name: Test

on:
  push:
    paths:
      - ".github/workflows/**"
      - "**.js"
      - "**.ts"
      - "**.json"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    name: Test with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
        env:
          CI: true
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json
          fail_ci_if_error: true
          verbose: true
