name: Test

on:
  push:
    paths:
      - ".github/workflows/**"
      - "**.js"
      - "**.ts"
      - "**.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm test
        env:
          CI: true
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json
          # flags: unittests
          # name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
